import { ApiProperty } from "@nestjs/swagger";

export class OracleLookupJudgeDTO {
  @ApiProperty() activeFlag: number;
  @ApiProperty() activeFromDate: Date;
  @ApiProperty() activeToDate: Date;
  @ApiProperty() address: string;
  @ApiProperty() courtId: number;
  @ApiProperty() districtId: number;
  @ApiProperty() fax: string;
  @ApiProperty() firstName: string;
  @ApiProperty() flagJudge: number;
  @ApiProperty() fromCourt: number;
  @ApiProperty() genNo: string;
  @ApiProperty() headLevelFlag: number;
  @ApiProperty() idNo: string;
  @ApiProperty() hudgeAssign: number;
  @ApiProperty() judgeCode: string;
  @ApiProperty() judgeName: string;
  @ApiProperty() judgeSalary: number;
  @ApiProperty() judgeSalaryStep: number;
  @ApiProperty() judgeStatus: number;
  @ApiProperty() judgeTypeId: number;
  @ApiProperty() lastName: string;
  @ApiProperty() moo: string;
  @ApiProperty() positionId: number;
  @ApiProperty() postCode: string;
  @ApiProperty() provinceId: number;
  @ApiProperty() refId: number;
  @ApiProperty() road: string;
  @ApiProperty() roomId: number;
  @ApiProperty() selectCode: string;
  @ApiProperty() signature: string;
  @ApiProperty() soi: string;
  @ApiProperty() subdistrictId: number;
  @ApiProperty() superId: number;
  @ApiProperty() tel: string;
  @ApiProperty() toCourt: number;
  @ApiProperty() titleId: number;
}