lists = [
    [
        "PC_LABOR_COMPLAINANT",
        "pc_labor_complainant",
        "PcLaborComplainant",
        [
            ["COMPLAINANT_ID" ,"complainantId"],
            ["COURT_ID" ,"courtId"],
            ["CREATED_BY" ,"createdBy"],
            ["CREATED_DATE" ,"createdDate"],
            ["UPDATED_BY" ,"updatedBy"],
            ["UPDATED_DATE" ,"updatedDate"],
            ["REMOVED_BY" ,"removedBy"],
            ["REMOVED_DATE" ,"removedDate"],
            ["ORDER_NO" ,"orderNo"],
            ["CASE_ID" ,"caseId"],
            ["COMPLAINANT_DETAIL" ,"complainantDetail"],
            ["ACCEPT_COMPLAINANT" ,"acceptComplainant"],
            ["APPOINTMENT_CONSIDER_DATE" ,"appointmentConsiderDate"],
            ["APPOINTMENT_CONSIDER_TIME" ,"appointmentConsiderTime"],
            ["COMPLAINANT_CODE_NO" ,"complainantCodeNo"],
            ["COMPLAINANT_CODE_YEAR" ,"complainantCodeYear"],
            ["COURT_ORDER_DETAIL" ,"courtOrderDetail"],
            ["JUDGE_ID" ,"judgeId"],
            ["REQUEST_COURT_ACTION_EMPLOYER" ,"requestCourtActionEmployer"],
            ["REQUEST_COURT_ACTION_EMPLOYER_DETAIL" ,"requestCourtActionEmployerDetail"],
            ["REQUEST_COURT_ORDER" ,"requestCourtOrder"],
            ["REQUEST_COURT_ORDER_DETAIL" ,"requestCourtOrderDetail"],
            ["REQUEST_COURT_RIGHT_OTHER" ,"requestCourtRightOther"],
            ["REQUEST_COURT_RIGHT_OTHER_DETAIL" ,"requestCourtRightOtherDetail"],
            ["TO_PUNISH" ,"toPunish"],
            ["TO_PUNISH_DETAIL" ,"toPunishDetail"],
            ["TO_REDUCE_WAGE" ,"toReduceWage"],
            ["TO_REDUCE_WAGE_DETAIL" ,"toReduceWageDetail"],
            ["TO_TERMINATED" ,"toTerminated"],
            ["TO_TERMINATED_DETAIL" ,"toTerminatedDetail"] ,
        ]
    ],
    [   
        "PC_LABOR_COMPLAINANT_ACCUSER",
        "pc_labor_complainant_accuser" , 
        "PcLaborComplainantAccuser",
        [
            [ "ACCUSER_ID","accuserId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "ORDER_NO","orderNo"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "ACCUSER_AGE","accuserAge"],
            [ "ACCUSER_BIRTHDATE","accuserBirthdate"],
            [ "ACCUSER_EMAIL","accuserEmail"],
            [ "ACCUSER_LASTNAME","accuserLastname"],
            [ "ACCUSER_LIT_TYPE_ID","accuserLitTypeId"],
            [ "ACCUSER_NAME","accuserName"],
            [ "ACCUSER_NAME_TITLE","accuserNameTitle"],
            [ "ACCUSER_NATIONAL_ID","accuserNationalId"],
            [ "ACCUSER_NATIONAL_ID_CARD","accuserNationalIdCard"],
            [ "ACCUSER_OCCUPATION_ID","accuserOccupationId"],
            [ "ACCUSER_ORDER_NO","accuserOrderNo"],
            [ "ACCUSER_PERSONAL_TYPE_ID","accuserPersonalTypeId"],
            [ "ACCUSER_RACE_ID","accuserRaceId"],
            [ "ACCUSER_SEX_ID","accuserSexId"],
            [ "ACCUSER_TEL","accuserTel"],
            [ "COMPLAINANT_ID","complainantId"],
        ]
    ],
    [
        "PC_LABOR_COMPLAINANT_ACCUSER_ADDRESS",
        "pc_labor_complainant_accuser_address" , 
        "PcLaborComplainantAccuserAddress",
        [
            ["ACCUSER_ADDRESS_ID" , "accuserAddressId"],
            ["CREATED_BY" , "createdBy"],
            ["CREATED_DATE" , "createdDate"],
            ["UPDATED_BY" , "updatedBy"],
            ["UPDATED_DATE" , "updatedDate"],
            ["REMOVED_BY" , "removedBy"],
            ["REMOVED_DATE" , "removedDate"],
            ["ORDER_NO" , "orderNo"],
            ["ADDRESS_NO" , "addressNo"],
            ["ADDRESS_TYPE_ID" , "addressTypeId"],
            ["COUNTRY_ID" , "countryId"],
            ["DISTRICT_ID" , "districtId"],
            ["COMPLAINANT_ACCUSER_ID" , "complainantAccuserId"],
            ["MOO" , "moo"],
            ["PHONE_NUMBER" , "phoneNumber"],
            ["POST" , "post"],
            ["PROVINCE_ID" , "provinceId"],
            ["ROAD" , "road"],
            ["SOI" , "soi"],
            ["SUB_DISTRICT_ID" , "subDistrictId"],
        ]
    ],
    [
        "PC_LABOR_COMPLAINANT_DEFENDANT",
        "pc_labor_complainant_defendant" , 
        "PcLaborComplainantDefendant",
        [
            ["DEFENDANT_ID" , "defendantId"],
            ["COMPLAINANT_ID" , "complainantId"],
            ["CREATED_BY" , "createdBy"],
            ["CREATED_DATE" , "createdDate"],
            ["UPDATED_BY" , "updatedBy"],
            ["UPDATED_DATE" , "updatedDate"],
            ["REMOVED_BY" , "removedBy"],
            ["REMOVED_DATE" , "removedDate"],
            ["ORDER_NO" , "orderNo"],
            ["DEFENDANT_AGE" , "defendantAge"],
            ["DEFENDANT_BIRTHDATE" , "defendantBirthdate"],
            ["DEFENDANT_EMAIL" , "defendantEmail"],
            ["DEFENDANT_LASTNAME" , "defendantLastname"],
            ["DEFENDANT_LIT_TYPE_ID" , "defendantLitTypeId"],
            ["DEFENDANT_NAME" , "defendantName"],
            ["DEFENDANT_NAME_TITLE" , "defendantNameTitle"],
            ["DEFENDANT_NATIONAL_ID" , "defendantNationalId"],
            ["DEFENDANT_NATIONAL_ID_CARD" , "defendantNationalIdCard"],
            ["DEFENDANT_OCCUPATION_ID" , "defendantOccupationId"],
            ["DEFENDANT_ORDER_NO" , "defendantOrderNo"],
            ["DEFENDANT_PERSONAL_TYPE_ID" , "defendantPersonalTypeId"],
            ["DEFENDANT_RACE_ID" , "defendantRaceId"],
            ["DEFENDANT_SEX_ID" , "defendantSexId"],
            ["DEFENDANT_TEL" , "defendantTel"],
        ]
    ], 
    [
        "PC_LABOR_COMPLAINANT_DEFENDANT_ADDRESS",
        "pc_labor_complainant_defendant_address" , 
        "PcLaborComplainantDefendantAddress",
        [
            ["DEFENDANT_ADDRESS_ID" ,"defendantAddressId"],
            ["CREATED_BY" ,"createdBy"],
            ["CREATED_DATE" ,"createdDate"],
            ["UPDATED_BY" ,"updatedBy"],
            ["UPDATED_DATE" ,"updatedDate"],
            ["REMOVED_BY" ,"removedBy"],
            ["REMOVED_DATE" ,"removedDate"],
            ["ORDER_NO" ,"orderNo"],
            ["ADDRESS_NO" ,"addressNo"],
            ["ADDRESS_TYPE_ID" ,"addressTypeId"],
            ["COUNTRY_ID" ,"countryId"],
            ["DISTRICT_ID" ,"districtId"],
            ["COMPLAINANT_DEFENDANT_ID" ,"complainantDefendantId"],
            ["MOO" ,"moo"],
            ["PHONE_NUMBER" ,"phoneNumber"],
            ["POST" ,"post"],
            ["PROVINCE_ID" ,"provinceId"],
            ["ROAD" ,"road"],
            ["SOI" ,"soi"],
            ["SUB_DISTRICT_ID" ,"subDistrictId"],
        ]
    ], 
    [
        "PC_LABOR_EXECUTION",
        "pc_labor_execution" , 
        "PcLaborExecution",
        [
            ["EXECUTION_ID" ,"executionId"],
            ["CASE_ID" ,"caseId"],
            ["CREATED_BY" ,"createdBy"],
            ["CREATED_DATE" ,"createdDate"],
            ["UPDATED_BY" ,"updatedBy"],
            ["UPDATED_DATE" ,"updatedDate"],
            ["REMOVED_BY" ,"removedBy"],
            ["REMOVED_DATE" ,"removedDate"],
            ["ORDER_NO" ,"orderNo"],
            ["EXECUTION_CODE" ,"executionCode"],
            ["EXECUTION_REQ_TYPE" ,"executionReqType"],
            ["NAME_TITLE" ,"nameTitle"],
            ["NAME" ,"name"],
            ["LASTNAME" ,"lastname"],
            ["AGE" ,"age"],
            ["NATIONAL_ID" ,"nationalId"],
            ["ADDRESS_NO" ,"addressNo"],
            ["ADDRESS_MOO" ,"addressMoo"],
            ["ADDRESS_SOI" ,"addressSoi"],
            ["ADDRESS_ROAD" ,"addressRoad"],
            ["ADDRESS_POST" ,"addressPost"],
            ["TOMBON_ID" ,"tombonId"],
            ["AMPHOE_ID" ,"amphoeId"],
            ["PROVINCE_ID" ,"provinceId"],
            ["PHONE_NO" ,"phoneNo"],
        ]
    ], 
    [
        "PC_LABOR_EXECUTION_DETAIL",
        "pc_labor_execution_detail" , 
        "PcLaborExecutionDetail",
        [
            ["DETAIL_ID" , "detailId"],
            ["EXECUTION_ID" , "executionId"],
            ["CREATED_BY" , "createdBy"],
            ["CREATED_DATE" , "createdDate"],
            ["UPDATED_BY" , "updatedBy"],
            ["UPDATED_DATE" , "updatedDate"],
            ["REMOVED_BY" , "removedBy"],
            ["REMOVED_DATE" , "removedDate"],
            ["ORDER_NO" , "orderNo"],
            ["HAS_PAY_DEPT" , "hasPayDept"],
            ["PAY_DEPT_AMOUNT" , "payDeptAmount"],
            ["NEVER_PAY_DEPT" , "neverPayDept"],
            ["RECEIVED_HIRE" , "receivedHire"],
            ["RECEIVED_DATE" , "receivedDate"],
            ["HAS_CENSUS_REGISTRATION" , "hasCensusRegistration"],
            ["CENSUS_REGISTRATION_DETAIL" , "censusRegistrationDetail"],
            ["HAS_CERTIFICATION" , "hasCertification"],
            ["CERTIFICATION_DETAIL" , "certificationDetail"],
            ["HAS_OTHER_DOCUMENT" , "hasOtherDocument"],
            ["OTHER_DOCUMENT_DETAIL" , "otherDocumentDetail"],
            ["HAS_MAP" , "hasMap"],
            ["HAS_PHOTO" , "hasPhoto"],
            ["HAS_COPY_CAR_REGISTRATION" , "hasCopyCarRegistration"],
            ["HAS_COPY_CERTIFICATION" , "hasCopyCertification"],
            ["HAS_OTHER" , "hasOther"],
            ["OTHER_DETAIL" , "otherDetail"],
            ["IS_AGREEMENT" , "isAgreement"],
            ["HAS_NOT_OVER_EXECUTION_VALUE" , "hasNotOverExecutionValue"],
            ["TRUSTEE_NAME" , "trusteeName"],
            ["SAVE_FEE" , "saveFee"],
            ["RENT_FEE" , "rentFee"],
            ["HAS_LAND_NOTICE" , "hasLandNotice"],
            ["HAS_FOREST_NOTICE" , "hasForestNotice"],
            ["CONFIRM_TO_CONFISCATE" , "confirmToConfiscate"],
            ["RECEIVED_FOR" , "receivedFor"],
            ["AMOUNT" , "amount"],
            ["PAYEE_NAME_TITLE" , "payeeNameTitle"],
            ["PAYEE_NAME" , "payeeName"],
            ["PAYEE_LASTNAME" , "payeeLastname"],
            ["PAYEE_AGE" , "payeeAge"],
            ["PAYEE_NATIONAL_ID" , "payeeNationalId"],
            ["PAYEE_ADDRESS_NO" , "payeeAddressNo"],
            ["PAYEE_ADDRESS_MOO" , "payeeAddressMoo"],
            ["PAYEE_ADDRESS_SOI" , "payeeAddressSoi"],
            ["PAYEE_ADDRESS_ROAD" , "payeeAddressRoad"],
            ["PAYEE_TOMBON_ID" , "payeeTombonId"],
            ["PAYEE_AMPHOE_ID" , "payeeAmphoeId"],
            ["PAYEE_PROVINCE_ID" , "payeeProvinceId"],
            ["PAYEE_ADDRESS_POST" , "payeeAddressPost"],
            ["PAYEE_PHONE_NO" , "payeePhoneNo"],
            ["IS_PAID" , "isPaid"],
            ["PAID_NO" , "paidNo"],
            ["IS_RECORD" , "isRecord"],
            ["RECORD_BOOK_NO" , "recordBookNo"],
            ["RECORD_BOOK_PAGE" , "recordBookPage"],
        ]
    ], 
    [
        "PC_LABOR_EXECUTION_PROCESS",
        "pc_labor_execution_process" , 
        "PcLaborExecutionProcess",
        [
            [ "PROCESS_ID","processId"],
            [ "EXECUTION_ID","executionId"],
            [ "EXECUTION_TYPE_ID","executionTypeId"],
            [ "DEFENDANT_ID","defendantId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ASSET_DETAIL","assetDetail"],
            [ "ASSET_LOCATION","assetLocation"],
            [ "COST_ESTIMATE","costEstimate"],
            [ "DEFENDANT_LASTNAME","defendantLastname"],
            [ "DEFENDANT_NAME","defendantName"],
            [ "DEFENDANT_ORDER_NO","defendantOrderNo"],
        ]
    ], 
    [
        "PC_LABOR_WITNESS",
        "pc_labor_witness" , 
        "PcLaborWitness",
        [
            ["WITNESS_ID" , "witnessId"],
            ["CREATED_BY" , "createdBy"],
            ["CREATED_DATE" , "createdDate"],
            ["UPDATED_BY" , "updatedBy"],
            ["UPDATED_DATE" , "updatedDate"],
            ["REMOVED_BY" , "removedBy"],
            ["REMOVED_DATE" , "removedDate"],
            ["ORDER_NO" , "orderNo"],
            ["WITNESS_NAME_TITLE" , "witnessNameTitle"],
            ["WITNESS_NAME" , "witnessName"],
            ["WITNESS_LASTNAME" , "witnessLastname"],
            ["WITNESS_AGE" , "witnessAge"],
            ["WITNESS_NATIONAL_ID" , "witnessNationalId"],
            ["WITNESS_ADDRESS_NO" , "witnessAddressNo"],
            ["WITNESS_ADDRESS_MOO" , "witnessAddressMoo"],
            ["WITNESS_ADDRESS_SOI" , "witnessAddressSoi"],
            ["WITNESS_ADDRESS_ROAD" , "witnessAddressRoad"],
            ["TOMBON_ID" , "tombonId"],
            ["AMPHOE_ID" , "amphoeId"],
            ["PROVINCE_ID" , "provinceId"],
            ["WITNESS_ADDRESS_POST" , "witnessAddressPost"],
            ["WITNESS_PHONE_NO" , "witnessPhoneNo"],
            ["CASE_ID" , "caseId"],
            ["REMARK" , "remark"],
            ["INDICTMENT_ID" , "indictmentId"],
        ]
    ], 
    [
        "PC_LABOR_INDICTMENT",
        "pc_labor_indictment" , 
        "PcLaborIndictment",
        [
            [ "INDICTMENT_ID","indictmentId"],
            [ "COURT_ID","courtId"],
            [ "CASE_ID","caseId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ANNUAL_HOLIDAY_AMOUNT","annualHolidayAmount"],
            [ "APPOINTMENT_CONSIDER_DATE","appointmentConsiderDate"],
            [ "APPOINTMENT_CONSIDER_TIME","appointmentConsiderTime"],
            [ "COMPENSATE_AMOUNT","compensateAmount"],
            [ "COMPENSATION_AMOUNT","compensationAmount"],
            [ "COMPENSATION_LAW","compensationLaw"],
            [ "COURT_ORDER_DETAIL","courtOrderDetail"],
            [ "DEFENDANT_PAID","defendantPaid"],
            [ "DEFENDANT_PAID_AMOUNT","defendantPaidAmount"],
            [ "DEFENDANT_PAID_DETAIL","defendantPaidDetail"],
            [ "ENTERPRISE_LABOR_RELATIONS_LAW","enterpriseLaborRelationsLaw"],
            [ "FOLLOW_AGREEMENT","followAgreement"],
            [ "FOLLOW_AGREEMENT_DETAIL","followAgreementDetail"],
            [ "FOLLOW_COMPENSATION","followCompensation"],
            [ "FOLLOW_COMPENSATION_DETAIL","followCompensationDetail"],
            [ "FOLLOW_HOME_WORKER_PROTECTION","followHomeWorkerProtection"],
            [ "FOLLOW_HOME_WORKER_PROTECTION_DETAIL","followHomeWorkerProtectionDetail"],
            [ "FOLLOW_LABOR_LAW","followLaborLaw"],
            [ "FOLLOW_LABOR_LAW_DETAIL","followLaborLawDetail"],
            [ "FOLLOW_OTHER_LAW","followOtherLaw"],
            [ "FOLLOW_OTHER_LAW_DETAIL","followOtherLawDetail"],
            [ "FOLLOW_RECRUITMENT_AND_JOB_PROTECTION","followRecruitmentAndJobProtection"],
            [ "FOLLOW_RECRUITMENT_AND_JOB_PROTECTION_DETAIL","followRecruitmentAndJobProtectionDetail"],
            [ "FOLLOW_RELATIONSHIP_LAW","followRelationshipLaw"],
            [ "FOLLOW_RELATIONSHIP_LAW_DETAIL","followRelationshipLawDetail"],
            [ "FOLLOW_SSO_LAW","followSsoLaw"],
            [ "FOLLOW_SSO_LAW_DETAIL","followSsoLawDetail"],
            [ "HOLIDAY_OT_AMOUNT","holidayOtAmount"],
            [ "HOLIDAY_WORK_AMOUNT","holidayWorkAmount"],
            [ "HOME_WORKER_PROTECTION_LAW","homeWorkerProtectionLaw"],
            [ "INDICTMENT_CODE_NO","indictmentCodeNo"],
            [ "INDICTMENT_CODE_YEAR","indictmentCodeYear"],
            [ "JUDGE_ID","judgeId"],
            [ "LABOR_PROTECTION_LAW","laborProtectionLaw"],
            [ "LABOR_RELATIONSHIP_LAW","laborRelationshipLaw"],
            [ "OT_AMOUNT","otAmount"],
            [ "OTHER_LAW","otherLaw"],
            [ "OTHER_LAW_DETAIL","otherLawDetail"],
            [ "RECRUITMENT_AND_JOB_PROTECTION_LAW","recruitmentAndJobProtectionLaw"],
            [ "REMARK","remark"],
            [ "REVOKE_DEFENDANT_CONSIDER","revokeDefendantConsider"],
            [ "REVOKE_DEFENDANT_CONSIDER_DETAIL","revokeDefendantConsiderDetail"],
            [ "SSO_LAW","ssoLaw"],
            [ "VIOLATE_DETAIL","violateDetail"],
            [ "WAGE_AMOUNT","wageAmount"],
            [ "WORK_AGREEMENT","workAgreement"],
            [ "WORK_CONTRACT","workContract"],
        ]
    ], 
    [
        "PC_LABOR_INDICTMENT_ACCUSER",
        "pc_labor_indictment_accuser" , 
        "PcLaborIndictmentAccuser",
        [
            ["ACCUSER_ID" , "accuserid"],
            ["CREATED_BY" , "createdby"],
            ["CREATED_DATE" , "createddate"],
            ["ORDER_NO" , "orderno"],
            ["REMOVED_BY" , "removedby"],
            ["REMOVED_DATE" , "removeddate"],
            ["UPDATED_BY" , "updatedby"],
            ["UPDATED_DATE" , "updateddate"],
            ["ACCUSER_AGE" , "accuserage"],
            ["ACCUSER_BIRTHDATE" , "accuserbirthdate"],
            ["ACCUSER_EMAIL" , "accuseremail"],
            ["ACCUSER_LASTNAME" , "accuserlastname"],
            ["ACCUSER_LIT_TYPE_ID" , "accuserlittypeid"],
            ["ACCUSER_NAME" , "accusername"],
            ["ACCUSER_NAME_TITLE" , "accusernametitle"],
            ["ACCUSER_NATIONAL_ID" , "accusernationalid"],
            ["ACCUSER_NATIONAL_ID_CARD" , "accusernationalidcard"],
            ["ACCUSER_OCCUPATION_ID" , "accuseroccupationid"],
            ["ACCUSER_ORDER_NO" , "accuserorderno"],
            ["ACCUSER_PERSONAL_TYPE_ID" , "accuserpersonaltypeid"],
            ["ACCUSER_RACE_ID" , "accuserraceid"],
            ["ACCUSER_SEX_ID" , "accusersexid"],
            ["ACCUSER_TEL" , "accusertel"],
            ["INDICTMENT_ID" , "indictmentid"],
        ]
    ], 
    [
        "PC_LABOR_INDICTMENT_ACCUSER_ADDRESS",
        "pc_labor_indictment_accuser_address" , 
        "PcLaborIndictmentAccuserAddress",
        [
            [ "ACCUSER_ADDRESS_ID","accuserAddressId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ADDRESS_NO","addressNo"],
            [ "ADDRESS_TYPE_ID","addressTypeId"],
            [ "COUNTRY_ID","countryId"],
            [ "DISTRICT_ID","districtId"],
            [ "INDICTMENT_ACCUSER_ID","indictmentAccuserId"],
            [ "MOO","moo"],
            [ "PHONE_NUMBER","phoneNumber"],
            [ "POST","post"],
            [ "PROVINCE_ID","provinceId"],
            [ "ROAD","road"],
            [ "SOI","soi"],
            [ "SUB_DISTRICT_ID","subDistrictId"],
        ]
    ], 
    [
        "PC_LABOR_INDICTMENT_DEFENDANT",
        "pc_labor_indictment_defendant" , 
        "PcLaborIndictmentDefendant",
        [
            [ "DEFENDANT_ID","defendantId"],
            [ "INDICTMENT_ID","indictmentId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "DEFENDANT_AGE","defendantAge"],
            [ "DEFENDANT_BIRTHDATE","defendantBirthdate"],
            [ "DEFENDANT_EMAIL","defendantEmail"],
            [ "DEFENDANT_LASTNAME","defendantLastname"],
            [ "DEFENDANT_LIT_TYPE_ID","defendantLitTypeId"],
            [ "DEFENDANT_NAME","defendantName"],
            [ "DEFENDANT_NAME_TITLE","defendantNameTitle"],
            [ "DEFENDANT_NATIONAL_ID","defendantNationalId"],
            [ "DEFENDANT_NATIONAL_ID_CARD","defendantNationalIdCard"],
            [ "DEFENDANT_OCCUPATION_ID","defendantOccupationId"],
            [ "DEFENDANT_ORDER_NO","defendantOrderNo"],
            [ "DEFENDANT_PERSONAL_TYPE_ID","defendantPersonalTypeId"],
            [ "DEFENDANT_RACE_ID","defendantRaceId"],
            [ "DEFENDANT_SEX_ID","defendantSexId"],
            [ "DEFENDANT_TEL","defendantTel"],
        ]
    ], 
    [
        "PC_LABOR_INDICTMENT_DEFENDANT_ADDRESS",
        "pc_labor_indictment_defendant_address" , 
        "PcLaborIndictmentDefendantAddress",
        [
            [ "DEFENDANT_ADDRESS_ID","defendantAddressId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ADDRESS_NO","addressNo"],
            [ "ADDRESS_TYPE_ID","addressTypeId"],
            [ "COUNTRY_ID","countryId"],
            [ "DISTRICT_ID","districtId"],
            [ "INDICTMENT_DEFENDANT_ID","indictmentDefendantId"],
            [ "MOO","moo"],
            [ "PHONE_NUMBER","phoneNumber"],
            [ "POST","post"],
            [ "PROVINCE_ID","provinceId"],
            [ "ROAD","road"],
            [ "SOI","soi"],
            [ "SUB_DISTRICT_ID","subDistrictId"],
        ]
    ], 
    [
        "PC_LABOR_CASE",
        "pc_labor_case" , 
        "PcLaborCase",
        [
            [ "LABOR_CASE_ID","laborCaseId"],
            [ "COURT_ID","courtId"],
            [ "CASE_ID","caseId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "CHECK_SEND_STATUS","checkSendStatus"],
            [ "IS_NOTICE_PROVINCIAL","isNoticeProvincial"],
            [ "JUDGE_ID","judgeId"],
            [ "NOTICE_PROVINCIAL_ID","noticeProvincialId"],
            [ "NOTICE_SEND_STATUS","noticeSendStatus"],
            [ "RELEASE_DATE","releaseDate"],
            [ "SEND_BY","sendBy"],
            [ "SEND_DATE","sendDate"],
            [ "SEND_FEE","sendFee"],
            [ "SEND_METHOD","sendMethod"],
        ]
    ], 
    [
        "PC_LABOR_CASE_ACCUSER_ADDRESS",
        "pc_labor_case_accuser_address" , 
        "PcLaborCaseAccuserAddress",
        [
            [ "ACCUSER_ADDRESS_ID","accuserAddressId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ADDRESS_NO","addressNo"],
            [ "ADDRESS_TYPE_ID","addressTypeId"],
            [ "COUNTRY_ID","countryId"],
            [ "DISTRICT_ID","districtId"],
            [ "LABOR_CASE_ACCUSER_ID","laborCaseAccuserId"],
            [ "MOO","moo"],
            [ "PHONE_NUMBER","phoneNumber"],
            [ "POST","post"],
            [ "PROVINCE_ID","provinceId"],
            [ "ROAD","road"],
            [ "SOI","soi"],
            [ "SUB_DISTRICT_ID","subDistrictId"],
        ]
    ], 
    [
        "PC_LABOR_CASE_DEFENDANT_ADDRESS",
        "pc_labor_case_defendant_address" , 
        "PcLaborCaseDefendantAddress",
        [
            [ "DEFENDANT_ADDRESS_ID","defendantAddressId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "ADDRESS_NO","addressNo"],
            [ "ADDRESS_TYPE_ID","addressTypeId"],
            [ "COUNTRY_ID","countryId"],
            [ "DISTRICT_ID","districtId"],
            [ "LABOR_CASE_DEFENDANT_ID","laborCaseDefendantId"],
            [ "MOO","moo"],
            [ "PHONE_NUMBER","phoneNumber"],
            [ "POST","post"],
            [ "PROVINCE_ID","provinceId"],
            [ "ROAD","road"],
            [ "SOI","soi"],
            [ "SUB_DISTRICT_ID","subDistrictId"],
        ]
    ], 
    [
        "PC_LABOR_CASE_ACCUSER",
        "pc_labor_case_accuser" , 
        "PcLaborCaseAccuser",
        [
            [ "ACCUSER_ID","accuserId"],
            [ "LABOR_CASE_ID","laborCaseId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "ORDER_NO","orderNo"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "ACCUSER_AGE","accuserAge"],
            [ "ACCUSER_BIRTHDATE","accuserBirthdate"],
            [ "ACCUSER_EMAIL","accuserEmail"],
            [ "ACCUSER_LASTNAME","accuserLastname"],
            [ "ACCUSER_LIT_TYPE_ID","accuserLitTypeId"],
            [ "ACCUSER_NAME","accuserName"],
            [ "ACCUSER_NAME_TITLE","accuserNameTitle"],
            [ "ACCUSER_NATIONAL_ID","accuserNationalId"],
            [ "ACCUSER_NATIONAL_ID_CARD","accuserNationalIdCard"],
            [ "ACCUSER_OCCUPATION_ID","accuserOccupationId"],
            [ "ACCUSER_ORDER_NO","accuserOrderNo"],
            [ "ACCUSER_PERSONAL_TYPE_ID","accuserPersonalTypeId"],
            [ "ACCUSER_RACE_ID","accuserRaceId"],
            [ "ACCUSER_SEX_ID","accuserSexId"],
            [ "ACCUSER_TEL","accuserTel"],
        ]
    ], 
    [
        "PC_LABOR_CASE_DEFENDANT",
        "pc_labor_case_defendant" , 
        "PcLaborCaseDefendant",
        [
            [ "DEFENDANT_ID","defendantId"],
            [ "LABOR_CASE_ID","laborCaseid"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "DEFENDANT_AGE","defendantAge"],
            [ "DEFENDANT_BIRTHDATE","defendantBirthdate"],
            [ "DEFENDANT_EMAIL","defendantEmail"],
            [ "DEFENDANT_LASTNAME","defendantLastname"],
            [ "DEFENDANT_LIT_TYPE_ID","defendantLittypeid"],
            [ "DEFENDANT_NAME","defendantName"],
            [ "DEFENDANT_NAME_TITLE","defendantNametitle"],
            [ "DEFENDANT_NATIONAL_ID","defendantNationalid"],
            [ "DEFENDANT_NATIONAL_ID_CARD","defendantNationalidcard"],
            [ "DEFENDANT_OCCUPATION_ID","defendantOccupationid"],
            [ "DEFENDANT_ORDER_NO","defendantOrderno"],
            [ "DEFENDANT_PERSONAL_TYPE_ID","defendantPersonaltypeid"],
            [ "DEFENDANT_RACE_ID","defendantRaceid"],
            [ "DEFENDANT_SEX_ID","defendantSexid"],
            [ "DEFENDANT_TEL","defendantTel"],
        ]
    ], 
    [
        "PC_LABOR_CASE_APPOINT",
        "pc_labor_case_appoint" , 
        "PcLaborCaseAppoint",
        [
            [ "LABOR_CASE_APPOINT_ID","laborCaseAppointId"],
            [ "CREATED_BY","createdBy"],
            [ "CREATED_DATE","createdDate"],
            [ "UPDATED_BY","updatedBy"],
            [ "UPDATED_DATE","updatedDate"],
            [ "REMOVED_BY","removedBy"],
            [ "REMOVED_DATE","removedDate"],
            [ "ORDER_NO","orderNo"],
            [ "APPOINT_REASON_ID","appointReasonId"],
            [ "LABOR_CASE_APPOINT_DATE","laborCaseAppointDate"],
            [ "LABOR_CASE_APPOINT_TIME","laborCaseAppointTime"],
            [ "LABOR_CASE_ID","laborCaseId"],
        ]
    ]
]

for x in lists:
    text = """import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
"""
    text += "@Entity({ name :" 
    text += "'{}'".format(x[0])
    text += "})"

    text += """
export class Oracle{}Details""".format(x[2])
    text += """{
        @PrimaryGeneratedColumn() xxx: number;
        """
    for y in x[3]:
        text += """@Column({""" 
        text += """name: '{}'""".format(y[0])
        text += "})"
        text += """ {} : string;
        """.format(y[1])
        
    text += """
        toResponseObject() {
                const responseObject = {};
                return responseObject;
            }
    }
    """
    f = open("src/business/pc-labor/oracle/"+x[1]+".entities.ts", "w")
    f.write(text)
    f.close()
