import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity({ name: "PC_PROCEED_CASE_CHECKLIST" })
export class OracleProceedCaseChecklists {
  @PrimaryGeneratedColumn({ name: "CHECKLIST_ID", comment: "รหัสข้อมูลการตรวจสำนวน(AUTO INCREMENT)" }) checklistId: number;
  @Column({ name: "ORDER_NO", nullable: true, comment: "ลำดับของข้อมูล" }) orderNo: number;
  @Column({ name: "ANSWER_1_1", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน) ข้อ 1  มีการสอบคำให้การ/รวมทั้งสอบถามเรื่องทนายหรือที่ปรึกษากฎหมายหรือไม่ (ที่ปรึกษาใช้เยาวชนฯ)" }) answer11: number;
  @Column({ name: "ANSWER_1_10_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 10 ตัวเลือกคำตอบ" }) answer110Choice: number;
  @Column({ name: "ANSWER_1_10_COURT", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 10 ศาล" }) answer110Court: string;
  @Column({ name: "ANSWER_1_10_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 10 สถานะ" }) answer110Status: number;
  @Column({ name: "ANSWER_1_11_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 11 ตัวเลือกคำตอบ" }) answer111Choice: number;
  @Column({ name: "ANSWER_1_11_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 11 สถานะ" }) answer111Status: number;
  @Column({ name: "ANSWER_1_12_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 12 ตัวเลือกคำตอบ" }) answer112Choice: number;
  @Column({ name: "ANSWER_1_12_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 12 สถานะ" }) answer112Status: number;
  @Column({ name: "ANSWER_1_13_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 13 ตัวเลือกคำตอบ" }) answer113Choice: number;
  @Column({ name: "ANSWER_1_13_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 13 สถานะ" }) answer113Status: number;
  @Column({ name: "ANSWER_1_14_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 14 ตัวเลือกคำตอบ" }) answer114Choice: number;
  @Column({ name: "ANSWER_1_14_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 14 สถานะ" }) answer114Status: number;
  @Column({ name: "ANSWER_1_15_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 15 ตัวเลือกคำตอบ" }) answer115Choice: number;
  @Column({ name: "ANSWER_1_15_DETAIL", nullable: true, comment: "รายละเอียดคำตอบ" }) answer115Detail: string;
  @Column({ name: "ANSWER_1_15_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 15 สถานะ" }) answer115Status: number;
  @Column({ name: "ANSWER_1_16", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 16" }) answer116: number;
  @Column({ name: "ANSWER_1_17", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 17" }) answer117: number;
  @Column({ name: "ANSWER_1_18", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 18" }) answer118: number;
  @Column({ name: "ANSWER_1_18_CHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 18 ตัวเลือกของคำตอบ, มีหนังสือแจ้งคู่ความให้แก้ไขเหตุขัดข้องแล้ว และตัวเลือกกรณีเลือกแก้ไขปัญหา" }) answer118ChoiceHaveFixed: number;
  @Column({ name: "ANSWER_1_18_CHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 18 ตัวเลือกของคำตอบ เจ้าหน้าที่ไม่สามารถแก้ไขเหตุขัดข้องได้ เห็นควรนัดประชุมคดีเพื่อแก้ไขเหตุขัดข้อง" }) answer118ChoiceNoneFixed: number;
  @Column({ name: "ANSWER_1_18_DETAIL", nullable: true, comment: "รายละเอียดคำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน)มล, ข้อที่ 18" }) answer118Detail: string;
  @Column({ name: "ANSWER_1_18_SUBCHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 18" }) answer118SubchoiceHaveFixed: number;
  @Column({ name: "ANSWER_1_18_SUBCHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 18" }) answer118SubchoiceNoneFixed: number;
  @Column({ name: "ANSWER_1_2", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 2 มีการสอบถามไกล่เกลี่ย / สมานฉันท์และสันติวิธีหรือไม่" }) answer12: number;
  @Column({ name: "ANSWER_1_3", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 3" }) answer13: number;
  @Column({ name: "ANSWER_1_4", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 4" }) answer14: number;
  @Column({ name: "ANSWER_1_5_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 5 ตัวเลือกคำตอบ" }) answer15Choice: number;
  @Column({ name: "ANSWER_1_5_DATE", type: "timestamp", comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 5 วันที่" }) answer15Date: Date;
  @Column({ name: "ANSWER_1_6", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 6" }) answer16: number;
  @Column({ name: "ANSWER_1_7_BLACKCASE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 7 เลขคดีดำ" }) answer17Blackcase: string;
  @Column({ name: "ANSWER_1_7_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 7 ตัวเลือกคำตอบ" }) answer17Choice: number;
  @Column({ name: "ANSWER_1_7_COURT", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 7 ศาล" }) answer17Court: string;
  @Column({ name: "ANSWER_1_7_REDCASE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 7 เลขคดีแดง" }) answer17Redcase: string;
  @Column({ name: "ANSWER_1_8_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 8 ตัวเลือกคำตอบ" }) answer18Choice: number;
  @Column({ name: "ANSWER_1_8_DATE", type: "timestamp", comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 8 วันที่" }) answer18Date: Date;
  @Column({ name: "ANSWER_1_8_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 8 สถานะ" }) answer18Status: number;
  @Column({ name: "ANSWER_1_9_CHOICE", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 9 ตัวเลือกคำตอบ" }) answer19Choice: number;
  @Column({ name: "ANSWER_1_9_STATUS", nullable: true, comment: "คำตอบส่วนที่ 1 ศูนย์ตรวจความพร้อมของสำนวน(ห้องเก็บสำนวน), ข้อที่ 9 สถานะ" }) answer19Status: number;
  @Column({ name: "ANSWER_2_1", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 1 แจ้งยืนยันวันนัดสืบพยานแก่คู่ความ" }) answer21: number;
  @Column({ name: "ANSWER_2_2", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 2 แจ้งเตือนให้มาเป็นพยาน พร้อมใบตอบรับ" }) answer22: number;
  @Column({ name: "ANSWER_2_3", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 3 มีการแจ้งให้แก้ไขเหตุขัดข้องหรือไม่" }) answer23: number;
  @Column({ name: "ANSWER_2_4", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 4 แจ้งตำรวจจัดทำบัญชีคุมพยานที่ต้องมาเบิก ความที่ศาล" }) answer24: number;
  @Column({ name: "ANSWER_2_5", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 5 ส่งตารางการเป็นพยานศาล" }) answer25: number;
  @Column({ name: "ANSWER_2_6", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 6 นำรายงานผลการส่งหมายเรียกพยานเข้า สำนวนและเสนอผู้บริหารศาลชั้นต้นทราบหรือไม่" }) answer26: number;
  @Column({ name: "ANSWER_2_7", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน ข้อที่ 7 มีสรุปรายงานผลการส่งหมายเรียกพยานและ เสนอผู้บริหารศาลชั้นต้นทราบหรือไม่" }) answer27: number;
  @Column({ name: "ANSWER_2_8", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8" }) answer28: number;
  @Column({ name: "ANSWER_2_8_CHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8 ตัวเลือกของคำตอบ, มีหนังสือแจ้งคู่ความให้แก้ไขเหตุขัดข้องแล้ว และตัวเลือกกรณีเลือกแก้ไขปัญหา" }) answer28ChoiceHaveFixed: number;
  @Column({ name: "ANSWER_2_8_CHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8 ตัวเลือกของคำตอบ เจ้าหน้าที่ไม่สามารถแก้ไขเหตุขัดข้องได้ เห็นควรนัดประชุมคดีเพื่อแก้ไขเหตุขัดข้อง" }) answer28ChoiceNoneFixed: number;
  @Column({ name: "ANSWER_2_8_OTHER_DETAIL", nullable: true, comment: "รายละเอียดคำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8" }) answer28OtherDetail: string;
  @Column({ name: "ANSWER_2_8_SUBCHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8" }) answer28SubchoiceHaveFixed: number;
  @Column({ name: "ANSWER_2_8_SUBCHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 2 ศูนย์ประสานงานพยาน, ข้อที่ 8" }) answer28SubchoiceNoneFixed: number;
  @Column({ name: "ANSWER_3_1", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 1 มีการตรวจสอบความพร้อมของสำนวนอีกครั้งหรือไม่" }) answer31: number;
  @Column({ name: "ANSWER_3_2", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 2 มีการขอให้สืบพยานล่วงหน้าหรือสืบพยานนอกเวลาทำการราชการปกติหรือไม่" }) answer32: number;
  @Column({ name: "ANSWER_3_2_COUNT", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 2 จำนวน" }) answer32Count: number;
  @Column({ name: "ANSWER_3_3", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความข้อที่ 3 มีการสืบพยานไว้ก่อนหรือไม่" }) answer33: number;
  @Column({ name: "ANSWER_3_3_COUNT", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 3 จำนวน" }) answer33Count: number;
  @Column({ name: "ANSWER_3_4", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 4 มีการตรวจสอบจำเลยว่าขังหรือประกัน" }) answer34: number;
  @Column({ name: "ANSWER_3_5", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 5 มีการให้นายประกันและจำเลยมารายงานตัว ก่อนวันนัดประมาณ 1 สัปดาห์หรือไม่" }) answer35: number;
  @Column({ name: "ANSWER_3_6", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 6, มีเหตุขัดข้อง : true / ไม่มีเหตุขัดข้อง : false" }) answer36: number;
  @Column({ name: "ANSWER_3_6_CHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ, ข้อที่ 6 ตัวเลือกของคำตอบ, มีหนังสือแจ้งคู่ความให้แก้ไขเหตุขัดข้องแล้ว และตัวเลือกกรณีเลือกแก้ไขปัญหา" }) answer36ChoiceHaveFixed: number;
  @Column({ name: "ANSWER_3_6_CHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ, ข้อที่ 6 ตัวเลือกของคำตอบ เจ้าหน้าที่ไม่สามารถแก้ไขเหตุขัดข้องได้ เห็นควรนัดประชุมคดีเพื่อแก้ไขเหตุขัดข้อง" }) answer36ChoiceNoneFixed: number;
  @Column({ name: "ANSWER_3_6_OTHER_DETAIL", nullable: true, comment: "รายละเอียดคำตอบคำตอบส่วนที่ 3 ศูนย์นัดความ ข้อที่ 6" }) answer36OtherDetail: string;
  @Column({ name: "ANSWER_3_6_SUBCHOICE_HAVE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ, ข้อที่ 6" }) answer36SubchoiceHaveFixed: number;
  @Column({ name: "ANSWER_3_6_SUBCHOICE_NONE_FIXED", nullable: true, comment: "คำตอบส่วนที่ 3 ศูนย์นัดความ, ข้อที่ 6" }) answer36SubchoiceNoneFixed: number;
  @Column({ name: "APPOINT_DATE", type: "timestamp", comment: "วันที่นัด" }) appointDate: Date;
  @Column({ name: "APPOINT_DETAIL", nullable: true, comment: "รายละเอียดนัดความ" }) appointDetail: string;
  @Column({ name: "APPOINT_PERIOD", comment: "นัดที่" }) appointPeriod: number;
  @Column({ name: "APPOINT_REASON_ID", nullable: true, comment: "รหัสเหตุนัดความ เชื่อมโยงตาราง PC_LOOKUP_OFFENSE" }) appointReasonId: number;
  @Column({ name: "CASE_ID", comment: "รหัสคดี เชื่อมโยงตาราง PC_CASE" }) caseId: number;
  @Column({ name: "CHECKLIST_DATE", type: "timestamp", comment: "วันที่ตรวจสอบ" }) checklistDate: Date;
  @Column({ name: "COLLAB_WITH_NAME", nullable: true, comment: "ชื่อผู้ประสานงาน" }) collabWithName: string;
  @Column({ name: "COURT_ID", comment: "รหัสศาล เชื่อมโยงตาราง PC_LOOKUP_COURT" }) courtId: number;
  @Column({ name: "EXPAND_DUEDATE_WORDING", nullable: true, comment: "ตัวเลือกอยู่ระหว่างการขยายระยะเวลาคำให้การ" }) expandDuedateWording: number;
  @Column({ name: "HAS_OTHER", nullable: true, comment: "ตัวเลือกอื่นๆ" }) hasOther: number;
  @Column({ name: "HAS_SEND_NOTICE_RESULT", nullable: true, comment: "ตัวเลือกรายงานผลการส่งหมายเรียก / หมายนัด / หมายแจ้งคำสั่ง" }) hasSendNoticeResult: number;
  @Column({ name: "HAVE_OBJECTIVES", nullable: true, comment: "ตัวเลือกมีเหตุขัดข้อง" }) haveObjectives: number;
  @Column({ name: "NOT_COMPLETED_WITNESS", nullable: true, comment: "ตัวเลือกเอกสาร พยานวัตถุยังไม่ครบ" }) notCompletedWitness: number;
  @Column({ name: "NOT_DEFENDANT_WORDING", nullable: true, comment: "ตัวเลือกจำเลยยังไม่ยื่นคำให้การ" }) notDefendantWording: number;
  @Column({ name: "NOT_DUEDATE_SEND_NOTICE", nullable: true, comment: "ตัวเลือกยังไม่ครบกำหนดการส่งหมาย" }) notDuedateSendNotice: number;
  @Column({ name: "NOT_DUEDATE_WORDING", nullable: true, comment: "ตัวเลือกยังไม่ครบกำหนดยื่นคำให้การ" }) notDuedateWording: number;
  @Column({ name: "NOT_HAVE_LAWYER_DEFENDANT", nullable: true, comment: "ตัวเลือกจำเลยยังไม่แต่งตั้งทนาย" }) notHaveLawyerDefendant: number;
  @Column({ name: "NOT_ISSUE_NOTICE", nullable: true, comment: "ตัวเลือกยังไม่ได้ออกหมายเรียก / หมายนัด / หมายแจ้งคำสั่ง" }) notIssueNotice: number;
  @Column({ name: "NOT_JUDGE_GROUP_INVITE", nullable: true, comment: "ตัวเลือกยังไม่ออกหนังสือเชิญผู้พิพากษาสมทบร่วมเป็นองค์คณะ" }) notJudgeGroupInvite: number;
  @Column({ name: "NOT_LIT_SEND_CONFIRMATION", nullable: true, comment: "ตัวเลือกคู่ความยังไม่ส่งบันทึกยืนยันข้อเท็จจริงแทนการสืบพยาน" }) notLitSendConfirmation: number;
  @Column({ name: "NOT_RECEIVED_WORDING_COURT", nullable: true, comment: "ตัวเลือกยังไม่ได้รับคำฟ้อง คำให้การ จากศาล" }) notReceivedWordingCourt: number;
  @Column({ name: "NOT_REPORT_SEND_NOTICE", nullable: true, comment: "ตัวเลือกยังไม่มีรายงานการส่งหมาย" }) notReportSendNotice: number;
  @Column({ name: "NOT_SEND_WITNESS", nullable: true, comment: "ตัวเลือกยังไม่ส่งเอกสาร พยานวัตถุเข้ามา" }) notSendWitness: number;
  @Column({ name: "OTHER_DETAIL", nullable: true, comment: "รายละเอียดอื่นๆ" }) otherDetail: string;
  @Column({ name: "WITNESS_NOTICE", nullable: true, comment: "ตัวเลือกหมายเรียกพยานเอกสาร พยานวัตถุ" }) witnessNotice: number;
  @Column({ name: "WORDING_COURT_DATE", type: "timestamp", comment: "ฉบับลงวันที่" }) wordingCourtDate: Date;
  @Column({ name: "WORDING_COURT_ID", nullable: true, comment: "รหัสศาล เชื่อมโยง PC_LOOKUP_COURT" }) wordingCourtId: number;
  @Column({ name: "APPOINT_TIME		VARCHAR2	20 CHAR	Y", nullable: true, comment: "เวลานัด" }) appointTime: string;
  @Column({ name: "CREATED_BY", comment: "รหัสผู้สร้างข้อมูล เชื่อมโยง PC_USER_PROFILE" }) createdBy: number;
  @Column({ name: "UPDATED_BY		NUMBER	38, 0	Y", nullable: true, comment: "รหัสผู้แก้ไขข้อมูลล่าสุด เชื่อมโยง PC_USER_PROFILE" }) updatedBy: number;
  @Column({ name: "REMOVED_BY", comment: "รหัสผู้ลบข้อมูล เชื่อมโยง PC_USER_PROFILE" }) removedBy: number;
  @Column({ name: "CREATED_DATE", type: "timestamp", comment: "วันเวลาที่สร้างข้อมูล" }) createdDate: Date;
  @Column({ name: "UPDATED_DATE", type: "timestamp", comment: "วันเวลาที่แก้ไขข้อมูลล่าสุด" }) updatedDate: Date;
  @Column({ name: "REMOVED_DATE", type: "timestamp", comment: "วันเวลาที่ลบข้อมูล" }) removedDate: Date;

  toResponseObject() {
    const { checklistId, orderNo, answer11, answer110Choice, answer110Court, answer110Status, answer111Choice, answer111Status, answer112Choice, answer112Status, answer113Choice, answer113Status, answer114Choice, answer114Status, answer115Choice, answer115Detail, answer115Status, answer116, answer117, answer118, answer118ChoiceHaveFixed, answer118ChoiceNoneFixed, answer118Detail, answer118SubchoiceHaveFixed, answer118SubchoiceNoneFixed, answer12, answer13, answer14, answer15Choice, answer15Date, answer16, answer17Blackcase, answer17Choice, answer17Court, answer17Redcase, answer18Choice, answer18Date, answer18Status, answer19Choice, answer19Status, answer21, answer22, answer23, answer24, answer25, answer26, answer27, answer28, answer28ChoiceHaveFixed, answer28ChoiceNoneFixed, answer28OtherDetail, answer28SubchoiceHaveFixed, answer28SubchoiceNoneFixed, answer31, answer32, answer32Count, answer33, answer33Count, answer34, answer35, answer36, answer36ChoiceHaveFixed, answer36ChoiceNoneFixed, answer36OtherDetail, answer36SubchoiceHaveFixed, answer36SubchoiceNoneFixed, appointDate, appointDetail, appointPeriod, appointReasonId, caseId, checklistDate, collabWithName, courtId, expandDuedateWording, hasOther, hasSendNoticeResult, haveObjectives, notCompletedWitness, notDefendantWording, notDuedateSendNotice, notDuedateWording, notHaveLawyerDefendant, notIssueNotice, notJudgeGroupInvite, notLitSendConfirmation, notReceivedWordingCourt, notReportSendNotice, notSendWitness, otherDetail, witnessNotice, wordingCourtDate, wordingCourtId, appointTime, createdBy, updatedBy, removedBy, createdDate, updatedDate, removedDate } = this;
    const responseObject = { checklistId, orderNo, answer11, answer110Choice, answer110Court, answer110Status, answer111Choice, answer111Status, answer112Choice, answer112Status, answer113Choice, answer113Status, answer114Choice, answer114Status, answer115Choice, answer115Detail, answer115Status, answer116, answer117, answer118, answer118ChoiceHaveFixed, answer118ChoiceNoneFixed, answer118Detail, answer118SubchoiceHaveFixed, answer118SubchoiceNoneFixed, answer12, answer13, answer14, answer15Choice, answer15Date, answer16, answer17Blackcase, answer17Choice, answer17Court, answer17Redcase, answer18Choice, answer18Date, answer18Status, answer19Choice, answer19Status, answer21, answer22, answer23, answer24, answer25, answer26, answer27, answer28, answer28ChoiceHaveFixed, answer28ChoiceNoneFixed, answer28OtherDetail, answer28SubchoiceHaveFixed, answer28SubchoiceNoneFixed, answer31, answer32, answer32Count, answer33, answer33Count, answer34, answer35, answer36, answer36ChoiceHaveFixed, answer36ChoiceNoneFixed, answer36OtherDetail, answer36SubchoiceHaveFixed, answer36SubchoiceNoneFixed, appointDate, appointDetail, appointPeriod, appointReasonId, caseId, checklistDate, collabWithName, courtId, expandDuedateWording, hasOther, hasSendNoticeResult, haveObjectives, notCompletedWitness, notDefendantWording, notDuedateSendNotice, notDuedateWording, notHaveLawyerDefendant, notIssueNotice, notJudgeGroupInvite, notLitSendConfirmation, notReceivedWordingCourt, notReportSendNotice, notSendWitness, otherDetail, witnessNotice, wordingCourtDate, wordingCourtId, appointTime, createdBy, updatedBy, removedBy, createdDate, updatedDate, removedDate };
    return responseObject;
  }
}